server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_campus_db
    username: root
    password: Ammunirala@123
    

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: smartCampusSecretKey1234567890smartCampusSecretKey
  expiration: 3600000

